lotr2-rl/LordsOfTheRealm2-v0:
    frame_stack: 4
    policy: 'CnnPolicy'
    n_envs: 1
    n_steps: 128
    n_epochs: 4
    batch_size: 256
    n_timesteps: !!float 1e7
    learning_rate: lin_2.5e-4
    clip_range: lin_0.1
    vf_coef: 0.5
    ent_coef: 0.01