lotr2-rl/LordsOfTheRealm2-v0:
    frame_stack: 10
    policy: 'CnnPolicy'
    n_envs: 1
    n_timesteps: !!float 1e5
    n_steps: 1000
    gae_lambda: 0.95
    gamma: 0.9
    n_epochs: 10
    ent_coef: 0.0
    learning_rate: !!float 1e-3
    clip_range: 0.2
    sde_sample_freq: 4
