# configs/my_custom_env.yaml
ppo-lotr2-rl/LordsOfTheRealm2-v0:
  n_timesteps: 10000
  policy: "MlpPolicy"
  n_envs: 1
  learning_rate: 0.0003
  ent_coef: 0.0


lotr2-rl/LordsOfTheRealm2-v0:
    n_envs: 1
    n_timesteps: !!float 1e5
    policy: 'MlpPolicy'
    n_steps: 1000
    gae_lambda: 0.95
    gamma: 0.9
    n_epochs: 10
    ent_coef: 0.0
    learning_rate: !!float 1e-3
    clip_range: 0.2
    use_sde: True
    sde_sample_freq: 4